name: Run Python Style Police

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-style-police:
    name: Python Style Police
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-24.04' }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install depends
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip setuptools wheel 
        pip install tox coverage-badge
    
    - name: Run format checker
      id: format-checker
      run: |
        tox -e formatcheck

  slack-workflow-status:
    if: ${{ always() && (github.repository_owner == 'WLAN-Pi') && (github.event.pull_request.head.repo.full_name == github.repository) }}
    name: Post Workflow Status to Slack
    needs:
      - python-style-police
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}