# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Python Tests

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  push:
    paths-ignore: # ignore files that don't change build output
      - '**.md'
      - .github/dependabot.yml
      - .gitignore
      - LICENSE
  pull_request:
    paths-ignore: # ignore files that don't change build output
      - '**.md'
      - .github/dependabot.yml
      - .gitignore
      - LICENSE

jobs:
  python:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install depends
      run: |
        sudo apt update
        sudo apt install build-essential git unzip zip nload tree ufw nftables vlan sqlite3 lldpd xxd dbus pkg-config gcc libpq-dev libdbus-glib-1-dev libglib2.0-dev cmake libdbus-1-dev python3-pip python3-dev python3-venv python3-wheel python3-setuptools
        sudo apt remove -y meson
        python -m ensurepip --upgrade
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade tox coverage-badge
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt --constraint <(echo "dbus-python; sys_platform != 'linux'"); fi
  
    - name: Run tests with tox
      id: tox-run
      run: |
        source venv/bin/activate
        tox

  slack-workflow-status:
    if: ${{ always() && (github.repository_owner == 'WLAN-Pi') && (! github.event.pull_request.head.repo.fork) }}
    name: Post Workflow Status to Slack
    needs:
      - python
    runs-on: "ubuntu-24.04"
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
